# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request - Docker

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/on-pullrequest-docker.yml"
      - "docker/*"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/on-pullrequest-docker.yml"
      - "docker/*"
  workflow_dispatch:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ods-api-db-admin/alpine/pgsql
          - ods-api-db-ods-minimal/alpine/pgsql
          - ods-api-db-ods-populated/alpine/pgsql
          - ods-api-swaggerui/alpine
          - ods-api-web-api/alpine/mssql
          - ods-api-web-api/alpine/pgsql
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter on Local Dockerfile
        with:
          dockerfile: docker/${{ matrix.image }}/Dockerfile

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Build all of the images
        # To confirm no errors occur. The "local" one will be built by the e2e
        # testing process.
        run: |
          ./get-versions.ps1
          ./build-images.ps1
        working-directory: docker
        shell: pwsh
